### ISSUE TITLE
problem with submitting maxfilter jobs

### ISSUE THREAD

**Issue by MadsJensen** [cfin-tools/stormdb#43]
Issue with submitting maxfilter jobs, I assume it resembles the previous issue #41  
```python
mf.submit()
Traceback (most recent call last):

  File "<ipython-input-18-844a5bd27173>", line 1, in <module>
    mf.submit()

  File "/users/mje/python_toolboxes/stormdb-python/stormdb/cluster.py", line 437, in submit
    job.submit(fake=fake)

  File "/users/mje/python_toolboxes/stormdb-python/stormdb/cluster.py", line 284, in submit
    m = re.search('(\d+)', output.rstrip())

  File "/users/mje/.conda/envs/py3/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)

TypeError: cannot use a string pattern on a bytes-like object

```

**Comment by cjayb** [comment]
jeps, beklager... skal også selv få styr på py3 på hyades. og unittests + CI!!
