### ISSUE TITLE
xscan fails

### ISSUE THREAD

**Issue by cjayb** [cfin-tools/stormdb#9]
``` python
mf.detect_bad_chans_xscan(in_fname=in_name[0], set_bad=True)

Traceback (most recent call last):

 File "<ipython-input-105-c0af46da0146>", line 1, in <module>
   mf.detect_bad_chans_xscan(in_fname=in_name[0], set_bad=True)

 File "/usr/local/common/meeg-cfin/stormdb/stormdb/process.py", line 100, in detect_bad_chans_xscan
   raise RuntimeError(errmsg)

RuntimeError: xscan exited with an error, output is:

usage: /neuro/bin/util/x86_64-pc-linux-gnu/xscan-3.0 -f <infile> [options]
'/neuro/bin/util/x86_64-pc-linux-gnu/xscan-3.0 -help' shows available options.
```

**Comment by cjayb** [comment]
Still have to figure out how to run xscan: it's resource-heavy so needs to be submitted to queue. But somehow we need to get information on the task completing, and a list of bad chans being available. This is a similar problem to figuring out how far one's maxfilter-runs have got in the queue.

**Comment by cjayb** [comment]
xscan is not yet production-ready, but you can submit it as a regular string using `submit_to_isis` (bash) or `Maxfilter.submit_to_isis(self, n_jobs=1, fake=False, submit_script=None)`.

See #10

**Comment by sarathykousik** [comment]
xscan failed on two control datasets as well but ran well all through the DBS datasets. That was weird to me. Changing the corr didn't really help.

**Comment by cjayb** [comment]
what does a "fail" look like? anything relevant in the logs?

**Comment by sarathykousik** [comment]
Log says:
"Program died due to signal 11, all output files were deleted!
Core dump disabled"

**Comment by cjayb** [comment]
Can you run Maxfilter on the same file without problem, though? With or without autobad? If so, could be an xscan bug, please send path to file so I can share with Elekta

**Comment by sarathykousik** [comment]
Yes. It runs fine with Maxfilter with autobad OFF and ON. but still fails with xscan.
